Update 0-change_your_home_IP

diff --git a/0x08-networking_basics_2/0-change_your_home_IP b/0x08-networking_basics_2/0-change_your_home_IP
--- a/0x08-networking_basics_2/0-change_your_home_IP
+++ b/0x08-networking_basics_2/0-change_your_home_IP
@@ -3,7 +3,15 @@
 # 	     - localhost resolves to 127.0.0.2
 #	     - facebook.com resolves to 8.8.8.8
 
-cp /etc/hosts ~/hosts.new
-sed -i s/127.0.0.1/127.0.0.2/ ~/hosts.new
-echo -e "8.8.8.8\tfacebook.com" >> ~/hosts.new
-cat ~/hosts.new > /etc/hosts
+TMP_FILE=/tmp/hosts.tmp
+sudo cp /etc/hosts $TMP_FILE
+sed -i s/127.0.0.1/127.0.0.2/ $TMP_FILE
+echo -e "8.8.8.8\tfacebook.com" >> $TMP_FILE
+
+if [ -f $TMP_FILE ]; then
+    sudo cat $TMP_FILE > /etc/hosts
+    rm $TMP_FILE
+else
+    echo "Error: Failed to modify hosts file"
+    exit 1
+fi
